### ISSUE TITLE
Version check in curl method

### ISSUE THREAD

**Issue by Insperio** [robclark56/TransferWise_PHP_SimpleAPIclass#1]
Hi, 

You got a logical error in the version check (curl method)

I suggest just replacing this:
`if(defined('PHP_MAJOR_VERSION') && (PHP_MAJOR_VERSION >= 5) &&  (PHP_MINOR_VERSION >= 4) && (PHP_RELEASE_VERSION >= 8)){`

with this:
`version_compare(PHP_VERSION, '5.4.8') >= 0`

or just removing that completely since nobody should be using php 5.6 or lower any more. 
See here: [supported php versions](https://www.php.net/supported-versions.php)

**Comment by robclark56** [comment]
Thank you for your feedback. I was not aware of the version_compare() function.

But I do not understand your comment "You got a logical error in the version check". In what way is my code incorrect?

**Comment by Insperio** [comment]
You are checking each digit of php version separately which is not the best
idea.
For example your version check fails for php 7.1.11. In this case php minor
version is 1 which is NOT bigger or equal 4. Hope it helps :)

**Comment by robclark56** [comment]
Indeed! You are correct. I have edited the code with your suggestion.

Thanks.
